FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
RUN npm install

FROM deps AS build
COPY . .
RUN npm run web:build

FROM nginx:1.27-alpine
COPY --from=build /app/apps/web/dist/web/browser /usr/share/nginx/html
EXPOSE 80
